name: Deploy, Install, Build & Run

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1

      - name: Deploy
        uses: actions/upload-artifact@v2
        with:
          path: /home/arthur/website

      - name: Install
        run: yarn

      - name: Build
        run: yarn build-all

      - name: Run
        run: yarn start