name: Deploy, Install, Build & Run

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1

      - name: Deploy
        uses: garygrossgarten/github-action-ssh@release
          with:
            command: cp . /home/arthur/website
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            passphrase: ${{ secrets.PASSPHRASE }}
            privateKey: ${{ secrets.KEY}}

      - name: Build
        run: yarn run build-all

      - name: Run
        run: yarn run start